project_name: openfga

before:
  hooks:
    - make generate-mocks

builds:
  -
    main: ./cmd/openfga
    binary: openfga
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
      - "-X github.com/openfga/openfga/internal/build.Version=v{{ .Version }}"
      - "-X github.com/openfga/openfga/internal/build.Commit={{.Commit}}"
      - "-X github.com/openfga/openfga/internal/build.Date={{.Date}}"
      - "-X github.com/openfga/openfga/internal/build.ProjectName={{.ProjectName}}"

dockers:
  - goos: linux
    goarch: amd64

    dockerfile: Dockerfile.goreleaser

    image_templates:
      - "shopsense/openfga:latest-amd64"
      - "shopsense/openfga:{{ .Tag }}-amd64"
      - "shopsense/openfga:v{{ .Version }}-amd64"
      - "shopsense/openfga:v{{ .Major }}-amd64"
      - "shopsense/openfga:v{{ .Major }}.{{ .Minor }}-amd64"
      - "shopsense/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"

    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

    extra_files:
      - assets

docker_manifests:
  - name_template: shopsense/openfga:latest
    image_templates:
      - shopsense/openfga:latest-amd64
  - name_template: shopsense/openfga:v{{ .Version }}
    image_templates:
      - shopsense/openfga:v{{ .Version }}-amd64
  - name_template: shopsense/openfga:v{{ .Major }}
    image_templates:
      - shopsense/openfga:v{{ .Major }}-amd64
  - name_template: shopsense/openfga:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - shopsense/openfga:v{{ .Major }}.{{ .Minor }}-amd64
  - name_template: shopsense/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - shopsense/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64

release:
  github:
    owner: sameer-m-dev
    name: openfga

sboms:
  - artifacts: archive

archives:
  - files:
      - assets

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
